### ISSUE TITLE
Working example

### ISSUE THREAD

**Issue by carlok** [ar4mirez/hapi-aws#1]
Hi
I tried to create a working example (AWS SQS) but I failed
the (broken) gist is at
https://gist.github.com/carlok/c008a1705ae17f5350a42235be6fbe15
notice that the promise works alone (without hapi and your plugin)
Am I using it wrongly? Where?
Secret keys and queue name are omitted.
Thanks

**Comment by ar4mirez** [comment]
Hi @carlok thanks for letting me know, I'm gonna checkout your example and see where is the issue. 👍

**Comment by cmiranda2012** [comment]
@carlok: You are missing `.aws.` in `server.plugins['hapi-aws'].aws.SQS.sendMessage(params).....`. We noticed there is an error in the documentation, where we failed to mention its inside of an object called `aws`. We plan to remove that object in the near future.

**Comment by carlok** [comment]
@cmiranda2012 thanks. I see so it's not going to be backward compatible... ;-( anyhow, let me try it now.

**Comment by ar4mirez** [comment]
@carlok we can do it backward compatible keep `.aws` and also be available in the root object. at least for the minor patch and give enough time until a major version and then deprecate it.

**Comment by carlok** [comment]
ok thanks. BTW: the script works now but I oddly have to duplicate/keep both options.global and services[0].options to have it work without errors or warnings. I mean, the global with access/secret/region and the sqs options with access/secret/region/apiVersion.

**Comment by ar4mirez** [comment]
can you show the error here please ? So we can take a look. Thanks.

**Comment by carlok** [comment]
sure.
omitting access/secret/region in the sqs options, I get
`{ ConfigError: Missing region in config
    at Request.VALIDATE_REGION (node_modules/aws-sdk/lib/event_listeners.js:80:45)
    at Request.callListeners (node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at callNextListener (node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at node_modules/aws-sdk/lib/event_listeners.js:74:9
    at finish (node_modules/aws-sdk/lib/config.js:313:7)
    at node_modules/aws-sdk/lib/config.js:355:9
    at resolveNext (node_modules/aws-sdk/lib/credentials/credential_provider_chain.js:107:9)
    at node_modules/aws-sdk/lib/credentials/credential_provider_chain.js:120:11
    at node_modules/aws-sdk/lib/credentials.js:123:23
    at node_modules/aws-sdk/lib/credentials/ec2_metadata_credentials.js:78:7
  message: 'Missing region in config',
  code: 'ConfigError',
  time: 2017-04-18T21:12:00.974Z } { ConfigError: Missing region in config
    at Request.VALIDATE_REGION (node_modules/aws-sdk/lib/event_listeners.js:80:45)
    at Request.callListeners (node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at callNextListener (node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at node_modules/aws-sdk/lib/event_listeners.js:74:9
    at finish (node_modules/aws-sdk/lib/config.js:313:7)
    at node_modules/aws-sdk/lib/config.js:355:9
    at resolveNext (node_modules/aws-sdk/lib/credentials/credential_provider_chain.js:107:9)
    at node_modules/aws-sdk/lib/credentials/credential_provider_chain.js:120:11
    at node_modules/aws-sdk/lib/credentials.js:123:23
    at node_modules/aws-sdk/lib/credentials/ec2_metadata_credentials.js:78:7
  message: 'Missing region in config',
  code: 'ConfigError',
  time: 2017-04-18T21:12:00.974Z }`

oh BTW: I have had to npm install "joi" to avoid an issue (it it not listed as a dependency but it seems to be needed to start) but this even this afternoon before the beginning of this issue

**Comment by ar4mirez** [comment]
@carlok got it @cmiranda2012 is looking at it 👍 I think is an issue coming from `aws-sdk` but we can do a quick fix in our end, about the `Joi` dependency thanks nice catch 👍 she will take care of it.
